import React from 'react';

export default function Disclaimer() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-4xl font-bold text-slate-900 mb-8">Disclaimer</h1>
      
      <div className="prose prose-indigo max-w-none text-slate-600 space-y-6">
        <p className="text-sm text-slate-500">Last updated: {new Date().toLocaleDateString()}</p>
        
        <p>
          The information provided by QRGen Pro on this website is for general informational purposes only. All information on the site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the site.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 mt-8 mb-4">1. External Links Disclaimer</h2>
        <p>
          The Site may contain links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.
        </p>
        <p>
          We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the site or any website or feature linked in any banner or other advertising.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 mt-8 mb-4">2. Tool Usage Disclaimer</h2>
        <p>
          The QR codes generated by our tool are created based on the exact input provided by the user. We are not responsible for the content, destination, or consequences of scanning any QR code generated through our platform. Users are solely responsible for ensuring that the data encoded in the QR codes complies with all applicable laws and regulations.
        </p>

        <h2 className="text-2xl font-semibold text-slate-800 mt-8 mb-4">3. No Professional Advice</h2>
        <p>
          The site cannot and does not contain professional advice. The information is provided for general informational and educational purposes only and is not a substitute for professional advice.
        </p>
        
        <h2 className="text-2xl font-semibold text-slate-800 mt-8 mb-4">4. "As Is" Basis</h2>
        <p>
          The QR code generator is provided on an "as is" and "as available" basis without any warranties of any kind, either express or implied. We do not guarantee that the tool will be uninterrupted, secure, or error-free.
        </p>
      </div>
    </div>
  );
}